### ISSUE TITLE
Allow running scripts with arguments

### ISSUE THREAD

**Issue by kornelski** [domenic/traceur-runner#2]
It's tricky to run scripts that depend on command-line arguments:
- every file path in arguments is run as JS, so `traceur-runner image-processor.js image.jpg` causes a torrent of errors
- `traceur-runner` is visible in `process.argv`

This confuses scripts, e.g.

``` sh
traceur-runner ./node_modules/.bin/mocha
```

causes endless loop.

**Comment by domenic** [comment]
Traceur Runner isn't really meant to be a drop-in `node.exe` replacement as of right now. I'd accept PRs to make it into one, but for my projects it's not necessary.
